### ISSUE TITLE
Nest parameters in the test

### ISSUE THREAD

**Issue by StevenNunez** [learn-co-curriculum/sinatra-pigeon#10]
https://github.com/learn-co-curriculum/sinatra-pigeon/blob/master/spec/controllers/pigeons_controller_spec.rb#L91

We should have these nested like they would be in forms.

```
 params = { pigeon: {
       :name   => "Phil",
       :gender => "male",
       :color  => "black, grey",
       :lives  => "Meatpacking District"
      }}
```
vs
```
 params = {
       :name   => "Phil",
       :gender => "male",
       :color  => "black, grey",
       :lives  => "Meatpacking District"
      }
```

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by aviflombaum** [comment]
@StevenNunez this lab is suppose to be an introduction to these concepts and I believe having an un-nested form in this lab is correct. It is way easier to understand a flat `params`. I'm closing this for now. @StevenNunez we can discuss, but I believe this lab is good.

**Comment by StevenNunez** [comment]
@aviflombaum  Maybe it's a difference in how we approach it. I never teach a flat params for something related to a domain concept. My class was thrown by the test since they were doing it 'right'. With the exception of the "id" field, you'd never have, or write a form with a flat params hash.
