### ISSUE TITLE
nested params

### ISSUE THREAD

**Issue by zonika** [learn-co-curriculum/sinatra-pigeon#14]
Can you nest the params in the last test so that they reflect the nested structure in the form names? right now it's giving 
params = {
        :name   => "Cher Ami",
        :gender => "female",
        :color  => "green, blue",
        :lives  => "Paris"
      }
when it should be giving
params = {
:pigeon =>{
        :name   => "Cher Ami",
        :gender => "female",
        :color  => "green, blue",
        :lives  => "Paris"}
      }
thanks

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by aviflombaum** [comment]
This is a duplicate of #10. Closing. Thanks very much for bringing this to our attention @zonika. I'm going to fix #10 now.
